import { createClient } from '@supabase/supabase-js';

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

export default async function handler(req, res) {
    // Gumroad sends a POST request after a successful purchase
    if (req.method !== 'POST') {
        return res.status(405).send('Method Not Allowed');
    }

    try {
        const body = req.body;
        
        // Extract data from Gumroad (License key is generated by Gumroad)
        const email = body.email;
        const licenseKey = body.license_key; // Standard Gumroad license key
        const product_name = body.product_name;

        // Set limits based on the product (Example: Pro Plan = 5000 requests)
        const maxLimit = 5000;

        // Insert or Update the user in Supabase
        const { error } = await supabase
            .from('usage_tracking')
            .upsert({ 
                license_key: licenseKey, 
                max_limit: maxLimit, 
                usage_count: 0 
            });

        if (error) throw error;

        console.log(`User ${email} activated with key ${licenseKey}`);
        return res.status(200).send('ShieldAI Activated');
        
    } catch (err) {
        console.error('Webhook Error:', err.message);
        return res.status(500).send('Internal Server Error');
    }
}
